services:
  # Database
  db:
    platform: linux/x86_64
    image: mariadb:lts-ubi9
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uni
      MYSQL_PASSWORD: password
    networks:
      - mariadb-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mariadb-phpmyadmin
networks:
  mariadb-phpmyadmin:

volumes:
  db_data:
