services:
  # Database
  db:
    platform: linux/x86_64
    image: mariadb:lts-ubi9
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uni
      MYSQL_PASSWORD: password
    networks:
      - mariadb-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mariadb-phpmyadmin
    volumes:
      - "/opt/docker/configs/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
      - "/opt/docker/configs/phpmyadmin/themes/blueberry:/var/www/html/themes/blueberry:ro"
      - "/opt/docker/configs/phpmyadmin/themes/darkwolf:/var/www/html/themes/darkwolf:ro"
      - "/opt/docker/configs/phpmyadmin/themes/boodark-orange:/var/www/html/themes/boodark-orange:ro"
networks:
  mariadb-phpmyadmin:

volumes:
  db_data:
